# Generated by Django 3.2 on 2021-07-17 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Фото альбом',
                'verbose_name_plural': 'Фото альбомы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(default='no-image.png', upload_to='images/gallery/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к фото')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('published', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='gallery.galleryalbum')),
            ],
        ),
    ]
