# Generated by Django 3.2.5 on 2021-07-21 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись к видео')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('published', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='gallery.galleryalbum')),
            ],
        ),
    ]
