# Generated by Django 3.2 on 2021-04-28 21:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('og_image', sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='images/opengraph', verbose_name='SEO Opengraph Image')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Описание')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, default='no-image.png', null=True, upload_to='images/pages', verbose_name='Картинка в шапке')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('published', models.BooleanField(default=True)),
                ('my_order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pages', to='core.page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('og_image', sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='images/opengraph', verbose_name='SEO Opengraph Image')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('price', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('my_order', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('og_image', sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='images/opengraph', verbose_name='SEO Opengraph Image')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content_html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Контент HTML')),
                ('published', models.BooleanField(default=True)),
                ('my_order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('page', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs', to='core.page', verbose_name='Страница')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
