# Generated by Django 3.2 on 2021-04-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_title',
        ),
    ]
