# Generated by Django 3.2 on 2021-04-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210428_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='seo_title',
        ),
    ]
