# Generated by Django 3.2 on 2021-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210428_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='button',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
