# Generated by Django 3.2 on 2021-04-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pageblock_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='core.page', verbose_name='Страница'),
        ),
    ]
