# Generated by Django 3.2 on 2021-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pageblock_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
