# Generated by Django 3.2 on 2021-04-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_price_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='price',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='seo_title',
        ),
    ]
