# Generated by Django 3.2 on 2021-04-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210429_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['my_order'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pageblock',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['my_order']},
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='button',
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='core.page'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buttons', to='core.pageblock')),
            ],
        ),
    ]
