# Generated by Django 3.2 on 2021-04-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210429_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='slug',
        ),
        migrations.AddField(
            model_name='button',
            name='href',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
