# Generated by Django 3.2 on 2021-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210429_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=200)),
                ('phone1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('vk', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ig', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
