# Generated by Django 3.2.5 on 2021-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210508_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='my_order',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
