# Generated by Django 3.2.5 on 2021-07-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_button_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
