# Generated by Django 3.2.5 on 2021-07-24 16:03

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_siteconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, default='no-image.png', null=True, upload_to='images/pages')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
                'ordering': ['created_date'],
            },
        ),
    ]
