# Generated by Django 3.2.5 on 2021-07-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210725_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblock',
            name='image',
        ),
    ]
