# Generated by Django 3.2.5 on 2021-07-25 13:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_pageblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='images/pageblock'),
        ),
    ]
