# Generated by Django 3.2.5 on 2021-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_title_comment_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
