# Generated by Django 3.2.5 on 2021-07-25 14:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_comment_fio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fio',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
