# Generated by Django 3.2.5 on 2021-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210725_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='smi_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
