# Generated by Django 3.2.5 on 2021-07-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_publication_smi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profession',
            new_name='role',
        ),
    ]
