# Generated by Django 3.2.5 on 2021-07-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_profession_comment_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
