# Generated by Django 3.2.5 on 2021-08-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210824_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='slogan_author',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
